# Generated by Django 5.0.1 on 2024-01-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_initial'),
        ('tasks', '0003_alter_task_creator_by_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='statuses.taskstatus'),
        ),
    ]
